### ISSUE TITLE
Erro ao executar o Grunt

### ISSUE THREAD

**Issue by filipeaguiar** [hitalos/frontend-skel#1]
Ao clonar o repositório, executei o npm install e instalei todas as dependências. Entretanto, ao executar o comando grunt, o seguinte erro aparece:

```
Running "serve" task

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue.

Aborted due to warnings.
```

**Comment by hitalos** [comment]
Realmente não tem essa task "serve". Deixei tudo na task default.
